# Generated by Django 4.2.3 on 2023-08-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coche",
            fields=[
                (
                    "matricula",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("fecha_matriculacion", models.DateField()),
                ("color", models.CharField(max_length=20)),
            ],
        ),
    ]
