# Generated by Django 4.2.3 on 2023-08-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("lugar", models.CharField(max_length=200)),
                (
                    "coche_implicado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.coche"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coche",
            name="accidentes",
            field=models.ManyToManyField(blank=True, to="api.accidente"),
        ),
    ]
