# Generated by Django 4.2.3 on 2023-08-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_accidente_coche_accidentes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accidente",
            name="coche_implicado",
        ),
        migrations.AddField(
            model_name="accidente",
            name="coches",
            field=models.ManyToManyField(blank=True, to="api.accidente"),
        ),
    ]
